spring:
  datasource:
    url: jdbc:mysql://94.191.63.206:3306/devtools?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: wojiuswo200
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001
log:
  level: info
  path: ./logs